ALTER TABLE users DROP COLUMN IF EXISTS audio_settings;
ALTER TABLE users DROP COLUMN IF EXISTS ranked_cooldown_until;
DROP INDEX IF EXISTS idx_rmp_abandon;
ALTER TABLE ranked_match_players DROP COLUMN IF EXISTS qr_penalty;
ALTER TABLE ranked_match_players DROP COLUMN IF EXISTS counted_abandon;
ALTER TABLE ranked_match_players DROP COLUMN IF EXISTS forfeit_reason;
ALTER TABLE ranked_match_players DROP COLUMN IF EXISTS final_hp;
ALTER TABLE ranked_answers DROP COLUMN IF EXISTS damage_target;
ALTER TABLE ranked_answers DROP COLUMN IF EXISTS damage;
DROP INDEX IF EXISTS idx_ranked_matches_reconnect;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS reconnects;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS disconnects;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS reconnect_deadline;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS disconnect_started_at;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS last_seen_at;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS forfeit_reason;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS result_reason;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS final_hp_p2;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS final_hp_p1;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS combo;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS hp_min;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS hp;
ALTER TABLE ranked_matches DROP COLUMN IF EXISTS start_hp;
DELETE FROM schema_migrations WHERE id = '032_ranked_battle_hp.sql';
